<template><div class="gradient-cover" :class="[cover.preset,{'is-animated':animate}]" :style="style"><canvas ref="canvas" aria-hidden="true" /></div></template>
<script setup>
import {ref,computed,onMounted,onBeforeUnmount,watch} from 'vue'
const props=defineProps({cover:{type:Object,required:true}}),canvas=ref(null),visible=ref(true),reduced=ref(false)
const animate=computed(()=>props.cover.animated&&!reduced.value&&visible.value)
const style=computed(()=>({'--g1':props.cover.colors?.[0]||'#c7d2fe','--g2':props.cover.colors?.[1]||'#fbcfe8','--g3':props.cover.colors?.[2]||'#bae6fd'}))
let gl,program,frame,observer,media
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function draw(time=0){if(!gl||!program)return;const c=canvas.value;const w=Math.min(1600,c.clientWidth*devicePixelRatio),h=Math.min(700,c.clientHeight*devicePixelRatio);if(c.width!==w||c.height!==h){c.width=w;c.height=h}gl.viewport(0,0,c.width,c.height);gl.uniform1f(gl.getUniformLocation(program,'t'),animate.value?time*.00012*(props.cover.speed||1):0);gl.uniform1f(gl.getUniformLocation(program,'seed'),props.cover.seed||0);gl.uniform1f(gl.getUniformLocation(program,'mode'),['mist','ribbon','grain','mesh'].indexOf(props.cover.preset));for(let i=0;i<3;i++){const hex=(props.cover.colors?.[i]||['#c7d2fe','#fbcfe8','#bae6fd'][i]).slice(1);gl.uniform3f(gl.getUniformLocation(program,'c'+i),parseInt(hex.slice(0,2),16)/255,parseInt(hex.slice(2,4),16)/255,parseInt(hex.slice(4,6),16)/255)}gl.drawArrays(gl.TRIANGLES,0,6);if(animate.value)frame=requestAnimationFrame(draw)}
function refresh(){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw)}
onMounted(()=>{media=matchMedia('(prefers-reduced-motion: reduce)');reduced.value=media.matches;media.addEventListener('change',onMotion);observer=new IntersectionObserver(entries=>{visible.value=entries[0].isIntersecting});observer.observe(canvas.value);try{gl=canvas.value.getContext('webgl',{alpha:false,preserveDrawingBuffer:true});if(!gl)return;program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 p; varying vec2 uv; void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float; varying vec2 uv; uniform float t,seed,mode; uniform vec3 c0,c1,c2;
void main(){vec2 p=uv;float a=sin(p.x*5.+p.y*3.+t+seed)*.5+.5;float b=cos(p.y*5.-p.x*2.-t*.7)*.5+.5;if(mode==1.)a=sin(p.x*8.+sin(p.y*5.+t)*2.+t)*.5+.5;if(mode==3.){a=smoothstep(0.,1.,distance(p,vec2(.3+.1*sin(t),.3)));b=smoothstep(0.,.8,distance(p,vec2(.8,.7)));}vec3 color=mix(mix(c0,c1,a),c2,b*.65);if(mode==2.)color+=(fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453)-.5)*.06;gl_FragColor=vec4(color,1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('link');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);refresh()}catch{program=null}})
function onMotion(e){reduced.value=e.matches}
watch([()=>props.cover,animate],refresh,{deep:true})
onBeforeUnmount(()=>{cancelAnimationFrame(frame);observer?.disconnect();media?.removeEventListener('change',onMotion);gl?.getExtension('WEBGL_lose_context')?.loseContext()})
</script>
<style scoped>.gradient-cover{width:100%;height:100%;background:radial-gradient(ellipse at 20% 30%,var(--g1),transparent 75%),radial-gradient(ellipse at 80% 60%,var(--g2),var(--g3))}.gradient-cover canvas{width:100%;height:100%;display:block}@media print{canvas{max-height:220px}}</style>
