<template><Teleport to="body"><Transition name="overlay" appear @after-leave="$emit('close')"><div v-if="visible" class="picker-dismiss" @pointerdown.self="visible=false" @keydown.esc="visible=false"><section class="icon-picker reader-dialog" :style="placement" role="dialog" aria-modal="true" aria-label="选择图标"><header class="picker-tabs"><button v-for="t in ['表情符号','图标','上传']" :key="t" :class="{selected:tab===t}" @click="tab=t;query=''">{{t}}</button><button class="remove-icon" :disabled="busy" @click="choose('')">移除</button></header>
<template v-if="tab!=='上传'"><div class="picker-search"><PhMagnifyingGlass :size="17"/><input ref="search" v-model="query" placeholder="筛选图标…" aria-label="筛选图标"/><button :disabled="busy" title="随机选择" @click="shuffle"><PhShuffle :size="19"/></button></div><div class="picker-scroll"><template v-for="group in groups" :key="group.name"><p>{{group.name}}</p><div class="icon-grid"><button v-for="item in group.items" :key="item.value" :title="item.label" :aria-label="item.label" :disabled="busy" @click="choose(item.value)"><ContentIcon :value="item.value" :size="27"/></button></div></template><p v-if="!groups.length">没有匹配的图标</p></div><footer v-if="tab==='表情符号'" class="picker-categories"><button v-for="(g,i) in emojiGroups" :key="g.name" :title="g.name" :class="{selected:category===g.name}" @click="category=category===g.name?'':g.name;query=''">{{['📚','🙂','🌿','🎨','🔶'][i]}}</button><button @click="category='';query=''">全部</button></footer></template>
<div v-else class="icon-upload"><div v-if="customIcons.length" class="uploaded-icons"><p>已上传</p><div class="icon-grid"><button v-for="icon in customIcons" :key="icon" type="button" title="使用已上传的图标" :disabled="busy" @click="choose(icon)"><ContentIcon :value="icon" :size="27" /></button></div></div><PhImage :size="38"/><p>选择一张图片作为图标</p><label class="reader-button">选择图片<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden @change="upload"/></label><p>PNG、JPEG、WebP 或 GIF，最大 10 MB</p></div><p v-if="error" class="reader-error">{{error}}</p></section></div></Transition></Teleport></template>
<script setup>
const visible=ref(true)
import {ref,computed,onMounted,onBeforeUnmount,nextTick} from 'vue'
import {PhMagnifyingGlass,PhShuffle,PhImage} from '@phosphor-icons/vue'
import ContentIcon from './ContentIcon.vue'
import {lineIcons,emojiGroups} from '../utils/icon-catalog'
import {API_BASE} from '../utils/api'
const props=defineProps({save:Function,anchor:Object});const emit=defineEmits(['close'])
const query=ref(''),busy=ref(false),error=ref(''),tab=ref('表情符号'),category=ref(''),search=ref(null),placement=ref({}),recent=ref([]),customIcons=ref([])
try{recent.value=JSON.parse(localStorage.getItem('reader:recent-icons')||'[]').filter(x=>typeof x==='string').slice(0,16)}catch{}
const groups=computed(()=>{let list=tab.value==='图标'?[{name:'图标',items:lineIcons}]:emojiGroups.filter(g=>!category.value||g.name===category.value);if(!query.value&&!category.value&&recent.value.length)list=[{name:'最近',items:recent.value.filter(x=>tab.value==='图标'?x.startsWith('icon:'):!x.startsWith('icon:')).map(value=>({value,label:value}))},...list];return list.map(g=>({...g,items:g.items.filter(x=>!query.value||x.label.toLowerCase().includes(query.value.toLowerCase())||x.value.includes(query.value))})).filter(g=>g.items.length)})
function place(){const r=props.anchor?.getBoundingClientRect?.();const w=Math.min(390,innerWidth-24);placement.value={position:'fixed',width:w+'px',left:Math.max(12,Math.min(r?.left??(innerWidth-w)/2,innerWidth-w-12))+'px',top:Math.max(12,Math.min(r?.bottom+10||90,innerHeight-Math.min(500,innerHeight-24)-12))+'px',maxHeight:'calc(100dvh - 24px)'}}
onMounted(()=>{place();window.addEventListener('resize',place);nextTick(()=>search.value?.focus());fetch(API_BASE+'/api/icon-history').then(r=>r.json()).then(json=>{if(json.ok&&Array.isArray(json.data))customIcons.value=json.data}).catch(()=>{})});onBeforeUnmount(()=>window.removeEventListener('resize',place))
async function choose(value){if(busy.value)return;busy.value=true;error.value='';try{if(value.startsWith('data:image/png;base64,')&&!customIcons.value.includes(value)){const response=await fetch(API_BASE+'/api/icon-history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})});const json=await response.json();if(json.ok)customIcons.value=json.data;else if(response.status!==403)throw Error(json.error||'图标历史保存失败')}await props.save(value);if(value&&!value.startsWith('data:')){recent.value=[value,...recent.value.filter(x=>x!==value)].slice(0,16);localStorage.setItem('reader:recent-icons',JSON.stringify(recent.value))}visible.value=false}catch(e){error.value=e.message}finally{busy.value=false}}
function shuffle(){const items=groups.value.flatMap(g=>g.items);if(items.length)choose(items[Math.floor(Math.random()*items.length)].value)}
async function upload(e){const f=e.target.files?.[0];if(!f)return;try{if(f.size>10*1024*1024)throw Error('请选择小于 10 MB 的图片');const bitmap=await createImageBitmap(f);const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const c=canvas.getContext('2d');const scale=Math.min(128/bitmap.width,128/bitmap.height);c.drawImage(bitmap,(128-bitmap.width*scale)/2,(128-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);bitmap.close();await choose(canvas.toDataURL('image/png'))}catch(e){error.value=e.message}}
</script>
<style scoped>
.picker-dismiss{position:fixed;inset:0;z-index:2200}.icon-picker{padding:14px;display:flex;flex-direction:column;box-shadow:var(--c-pop-shadow);border:0}.picker-tabs{display:flex;gap:18px;margin:0 0 14px;font-size:14px}.picker-tabs button{font-size:14px!important;padding:5px 0!important;color:var(--c-faint)}.picker-tabs .selected{color:var(--c-ink);font-weight:600}.picker-tabs .remove-icon{margin-left:auto;font-size:12px!important}.picker-search{display:flex;align-items:center;gap:8px;background:var(--c-field);padding:3px 10px;border-radius:var(--radius-control)}.picker-search input{border:0!important;background:none!important;margin:0!important;min-width:0}.picker-search:focus-within{box-shadow:0 0 0 2px var(--c-active)}.picker-scroll{height:320px;max-height:55dvh;overflow:auto;padding:4px 0}.picker-scroll p{margin:16px 4px 8px}.icon-grid{display:grid;grid-template-columns:repeat(8,1fr);gap:1px}.icon-grid button{height:40px;display:grid;place-items:center;border-radius:var(--radius-control)}.icon-grid button:hover,.picker-categories .selected{background:var(--c-hover)}.picker-categories{justify-content:space-between;margin-top:8px!important;gap:3px!important}.picker-categories button{padding:6px 9px;border-radius:var(--radius-control);font-size:17px}.picker-categories button:last-child{font-size:12px}.icon-upload{text-align:center;padding:24px 0}.icon-upload>svg{margin:auto;color:var(--c-faint)}
.uploaded-icons{text-align:left;margin:0 0 22px}.uploaded-icons p{margin:0 0 8px;color:var(--c-sub);font-size:12px}.uploaded-icons .icon-grid{grid-template-columns:repeat(auto-fill,minmax(40px,1fr));gap:4px}.uploaded-icons .icon-grid button{background:var(--c-field)}
</style>

<style scoped>.picker-tabs{gap:5px}.picker-tabs button{padding:6px 10px!important;border-radius:var(--radius-surface);font-weight:400!important}.picker-tabs .selected{background:var(--c-field)}.picker-tabs button:hover{background:var(--c-hover)}.picker-tabs .remove-icon{padding:6px!important}.icon-picker{border:1px solid var(--c-line)}</style>
