<template><Teleport to="body"><Transition name="overlay" appear @after-leave="$emit('close')"><div v-if="visible" class="reader-modal-shade" @click.self="visible=false"><section class="reader-dialog" role="dialog" aria-modal="true" aria-label="插入内容"><header><b>{{initial?'编辑内容':'插入内容'}}</b><button @click="visible=false">×</button></header><label>内容形式<select v-model="value.type"><option value="callout">提示块</option><option value="columns">双栏内容</option><option value="figure">图片与说明</option><option value="card">文档卡片</option></select></label><template v-if="value.type==='callout'"><label>符号<input v-model="value.icon" maxlength="8" /></label><label>内容<textarea v-model="value.content" /></label></template><template v-if="value.type==='columns'"><label>左栏<textarea v-model="value.left" /></label><label>右栏<textarea v-model="value.right" /></label><p>手机与打印时会自动排列为单栏。</p></template><template v-if="value.type==='figure'"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" @change="upload" /><label>图片说明<input v-model="value.caption" /></label><label>替代文字<input v-model="value.alt" /></label><label>宽度 {{value.width}}%<input type="range" v-model.number="value.width" min="20" max="100" /></label><label>对齐<select v-model="value.align"><option value="left">左</option><option value="center">中</option><option value="right">右</option></select></label></template><template v-if="value.type==='card'"><label>文档<select v-model="value.id" @change="pickDoc"><option v-for="doc in store.allFiles" :key="doc.id" :value="doc.id">{{doc.name}}</option></select></label><label>显示名称<input v-model="value.title" /></label><label>说明<textarea v-model="value.description" /></label></template><p>提示块和双栏内容支持常用 Markdown。插入后双击内容可修改。</p><p v-if="error" class="reader-error">{{error}}</p><footer><button class="reader-button" :disabled="busy" @click="save">{{initial?'更新':'插入'}}</button><button @click="visible=false">取消</button></footer></section></div></Transition></Teleport></template>
<script setup>
const visible=ref(true)
import {ref} from 'vue'
import {useDocsStore} from '../stores/docs'
import {API_BASE} from '../utils/api'
const props=defineProps({initial:Object}),emit=defineEmits(['close']),store=useDocsStore()
const path=store.currentPath,value=ref({version:1,type:'callout',icon:'💡',content:'',left:'',right:'',src:'',alt:'',caption:'',align:'center',width:100,id:'',title:'',description:'',...props.initial?.value}),error=ref(''),busy=ref(false)
function pickDoc(){value.value.title=store.allFiles.find(x=>x.id===value.value.id)?.name||''}
function save(){if(value.value.type==='figure'&&!value.value.src){error.value='请先选择图片';return}if(value.value.type==='card'&&!value.value.id){error.value='请选择文档';return}window.dispatchEvent(new CustomEvent('reader-insert-block',{detail:{path,value:value.value,pos:props.initial?.pos,previous:props.initial?.raw}}));visible.value=false}
async function upload(e){const f=e.target.files?.[0];if(!f)return;busy.value=true;try{if(f.size>10*1024*1024)throw Error('图片不能超过 10 MB');const data=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(f)});const res=await fetch(API_BASE+'/api/asset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,mime:f.type,base64:String(data).split(',')[1]})});const out=await res.json();if(!out.ok)throw Error(out.error);value.value.src=out.data.url;value.value.alt=f.name}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
