import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { BRAND_NAME, BRAND_DESCRIPTION_ZH, BRAND_DESCRIPTION_EN } from '../brand.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const check = process.argv.includes('--check')
const changes = []
function sync(relative, content) {
  const file = path.join(root, relative)
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return
  changes.push(relative)
  if (!check) fs.writeFileSync(file, content)
}
const module = '// Generated by scripts/sync-brand.mjs from brand.mjs.\n' +
  `export const BRAND_NAME = ${JSON.stringify(BRAND_NAME)}\n`
sync('server/brand.js', module)
sync('plugins/reader-workspace/brand.js', module)
const plugin = 'plugins/reader-workspace/'
const previous = JSON.parse(fs.readFileSync(path.join(root, plugin, 'locale/en.json'), 'utf8')).meta.title
for (const [locale, description] of [['zh', BRAND_DESCRIPTION_ZH], ['en', BRAND_DESCRIPTION_EN]]) {
  const relative = plugin + `locale/${locale}.json`
  const value = JSON.parse(fs.readFileSync(path.join(root, relative), 'utf8'))
  value.meta = { ...value.meta, title: BRAND_NAME, description }
  sync(relative, JSON.stringify(value, null, 2) + '\n')
}
for (const relative of ['package.json', plugin + 'package.json']) {
  const value = JSON.parse(fs.readFileSync(path.join(root, relative), 'utf8'))
  value.description = `${BRAND_NAME}: ${BRAND_DESCRIPTION_EN}`
  sync(relative, JSON.stringify(value, null, 2) + '\n')
}
const clientFile = plugin + 'client.js'
const client = fs.readFileSync(path.join(root, clientFile), 'utf8')
const declaration = `    const BRAND_NAME = ${JSON.stringify(BRAND_NAME)} // @generated-brand`
if (!/    const BRAND_NAME = .*\/\/ @generated-brand/.test(client)) throw Error('Missing client brand marker')
sync(clientFile, client.replace(/    const BRAND_NAME = .*\/\/ @generated-brand/, declaration))
const kb = JSON.parse(fs.readFileSync(path.join(root, 'public/kb.json'), 'utf8'))
sync('public/kb.json', JSON.stringify({ ...kb, title: BRAND_NAME }, null, 2) + '\n')

// Markdown stays directly readable on Git hosting. Rename prose, never commands or URLs.
if (previous !== BRAND_NAME) {
  function walk(dir) {
    return fs.readdirSync(path.join(root, dir), { withFileTypes: true }).flatMap(item => {
      const relative = path.join(dir, item.name)
      return item.isDirectory() ? walk(relative) : item.name.endsWith('.md') ? [relative] : []
    })
  }
  const docs = ['README.md', 'CHANGELOG.md', plugin + 'README.md', ...walk('docs'), ...walk('demo'), ...walk(plugin + 'skills')]
  for (const relative of docs) {
    const chunks = fs.readFileSync(path.join(root, relative), 'utf8').split(/(```[\s\S]*?```|`[^`\n]+`|https?:\/\/[^\s)]+)/g)
    for (let i = 0; i < chunks.length; i += 2) chunks[i] = chunks[i].split(previous).join(BRAND_NAME)
    sync(relative, chunks.join(''))
  }
}
if (check && changes.length) {
  console.error('Brand metadata out of sync: ' + changes.join(', '))
  process.exitCode = 1
} else console.log(check ? 'Brand metadata is consistent' : 'Brand metadata synchronized')
